version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thunderbot-backend
    ports:
      - '5000:5000'
    environment:
      - RESEND_API_KEY={RESEND_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules